CREATE TABLE LOGIN (
	LOGIN VARCHAR(30) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    CONSTRAINT PK_Login PRIMARY KEY (LOGIN,SENHA)
);

CREATE TABLE CLIENTE (
	NOME VARCHAR(60),
    CPF TEXT(14),
    TELEFONE VARCHAR(14),
    CELULAR VARCHAR(14),
    DATA_NASCIMENTO DATE,
    GENERO VARCHAR(1),
    SENHA VARCHAR(20),
    CONFIRMAR_SENHA VARCHAR(20)
);

#####################################################

CREATE TABLE DOCES (
	IdDoce INTEGER PRIMARY KEY AUTO_INCREMENT,
	CATEGORIA TEXT,
    FOREIGN KEY (CATEGORIA) REFERENCES TBL_MERCADORIAS(COD_MERCADORIA)
);

#####################################################

CREATE TABLE CHOCOLATE (
	CODIGO INTEGER PRIMARY KEY,
	CATEGORIA TEXT,
    DESCRICAO TEXT,
    QTDESTQ INTEGER,
    PRECO REAL
);
    
CREATE TABLE TRUFA (
	CODIGO INTEGER PRIMARY KEY,
    CATEGORIA TEXT,
    DESCRICAO TEXT,
    QTDESTQ INTEGER,
    PRECO REAL
);
    
CREATE TABLE BISCOITO (
	CODIGO INTEGER PRIMARY KEY,
    CATEGORIA TEXT,
    DESCRICAO TEXT,
    QTDESTQ INTEGER,
    PRECO REAL
);

CREATE TABLE CAFE (
	
);

CREATE TABLE BOLO (
	
);