CREATE TABLE LOGIN (
	LOGIN VARCHAR(30),
    SENHA VARCHAR(20),
    CONSTRAINT PK_Login PRIMARY KEY (LOGIN,SENHA)
);
CREATE TABLE CLIENTE (
	IdCLIENTE INTEGER PRIMARY KEY auto_increment,
	NOME VARCHAR(60),
    CPF VARCHAR(14),
    TELEFONE VARCHAR(14),
    EMAIL VARCHAR(50),
    DATANASCIMENTO VARCHAR(12),
    GENERO VARCHAR(25),
    LOGIN VARCHAR(20),
    SENHA VARCHAR(20)
);
CREATE TABLE CHOCOLATE (
	CODIGO INTEGER PRIMARY KEY,
	CATEGORIA TEXT,
    DESCRICAO TEXT,
    QTDESTQ INTEGER,
    PRECO REAL
);
CREATE TABLE TRUFA (
	CODIGO INTEGER PRIMARY KEY,
    CATEGORIA TEXT,
    DESCRICAO TEXT,
    QTDESTQ INTEGER,
    PRECO REAL
);
CREATE TABLE BISCOITO (
	CODIGO INTEGER PRIMARY KEY,
    CATEGORIA TEXT,
    DESCRICAO TEXT,
    QTDESTQ INTEGER,
    PRECO REAL
);